// Navigation bar item list. The page lists in the top menu
// and the urls to go to are set in the object below.
const navigationBarItems = [
	{
		name: "homepage",
		label: "Home Page",
		displayType: "icon",
		iconUrl: "/flex-playground-logo.png",
		redirectUrl: "/",
		isRedirectToOutside: false,
	},
	{
		name: "documentation",
		label: "Documentation",
		displayType: "text",
		iconUrl: null,
		redirectUrl: "/docs",
		isRedirectToOutside: false,
	},
	{
		name: "playground",
		label: "Playground",
		displayType: "text",
		iconUrl: null,
		redirectUrl: "/playground",
		isRedirectToOutside: false,
	},
	{
		name: "github",
		label: "GitHub",
		displayType: "text",
		iconUrl: null,
		redirectUrl: "https://github.com/findokan/flex-playground",
		isRedirectToOutside: true,
	},
];

// The Playground object initially starts with a root object
// and a state containing 2 boxes. The following object indicates this.
const initialPlaygroundState = {
	id: "pgRoot",
	label: "root",
	styleAttributes: {
		flex: {
			direction: "ltr",
			flexDirection: "row",
			basis: "auto",
			grow: 0,
			shrink: 1,
			flexWrap: "nowrap",
		},
		alignment: {
			justifyContent: "flex-start",
			alignItems: "stretch",
			alignSelf: "auto",
			alignContent: "stretch",
		},
		layout: {
			width: 500,
			height: 500,
			maxWidth: null,
			maxHeight: null,
			minWidth: null,
			minHeight: null,
			aspectRatio: "auto",
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0,
			borderTop: 1,
			borderRight: 1,
			borderBottom: 1,
			borderLeft: 1,
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			positionType: "relative",
			top: null,
			right: null,
			bottom: null,
			left: null,
		},
	},
	children: [
		{
			id: "1",
			label: "1",
			styleAttributes: {
				flex: {
					direction: "ltr",
					flexDirection: "row",
					basis: "auto",
					grow: 0,
					shrink: 1,
					flexWrap: "no-wrap",
				},
				alignment: {
					justifyContent: "flex-start",
					alignItems: "stretch",
					alignSelf: "auto",
					alignContent: "stretch",
				},
				layout: {
					width: 100,
					height: 100,
					maxWidth: null,
					maxHeight: null,
					minWidth: null,
					minHeight: null,
					aspectRatio: "auto",
					paddingTop: 0,
					paddingRight: 0,
					paddingBottom: 0,
					paddingLeft: 0,
					borderTop: 1,
					borderRight: 1,
					borderBottom: 1,
					borderLeft: 1,
					marginTop: 0,
					marginRight: 0,
					marginBottom: 0,
					marginLeft: 0,
					positionType: "relative",
					top: null,
					right: null,
					bottom: null,
					left: null,
				},
			},
			children: [],
		},
		{
			id: "2",
			label: "2",
			styleAttributes: {
				flex: {
					direction: "ltr",
					flexDirection: "row",
					basis: "auto",
					grow: 0,
					shrink: 1,
					flexWrap: "no-wrap",
				},
				alignment: {
					justifyContent: "flex-start",
					alignItems: "stretch",
					alignSelf: "auto",
					alignContent: "stretch",
				},
				layout: {
					width: 100,
					height: 100,
					maxWidth: null,
					maxHeight: null,
					minWidth: null,
					minHeight: null,
					aspectRatio: "auto",
					paddingTop: 0,
					paddingRight: 0,
					paddingBottom: 0,
					paddingLeft: 0,
					borderTop: 1,
					borderRight: 1,
					borderBottom: 1,
					borderLeft: 1,
					marginTop: 0,
					marginRight: 0,
					marginBottom: 0,
					marginLeft: 0,
					positionType: "relative",
					top: null,
					right: null,
					bottom: null,
					left: null,
				},
			},
			children: [],
		},
	],
};

export { navigationBarItems, initialPlaygroundState };
